"""Add unique field for customer migration.

Revision ID: 65c45b6b5fae
Revises: 7404300ffe34
Create Date: 2021-12-22 21:58:57.947807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c45b6b5fae'
down_revision = '7404300ffe34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'customer', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='unique')
    # ### end Alembic commands ###
