language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
script:
  - python -m pylint run.py
  - coverage run -m unittest discover crm/tests
  - coverage report
after_success:
  - coveralls